# Generated by Django 5.1.7 on 2025-04-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='times_bought',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
