# Generated by Django 5.1.7 on 2025-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
