/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsermanagementImport } from './routes/usermanagement'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as FeedbackImport } from './routes/feedback'
import { Route as FaqImport } from './routes/faq'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as MenuAddMenuImport } from './routes/menu/add-menu'

// Create/Update Routes

const UsermanagementRoute = UsermanagementImport.update({
  id: '/usermanagement',
  path: '/usermanagement',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FeedbackRoute = FeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MenuAddMenuRoute = MenuAddMenuImport.update({
  id: '/menu/add-menu',
  path: '/menu/add-menu',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/usermanagement': {
      id: '/usermanagement'
      path: '/usermanagement'
      fullPath: '/usermanagement'
      preLoaderRoute: typeof UsermanagementImport
      parentRoute: typeof rootRoute
    }
    '/menu/add-menu': {
      id: '/menu/add-menu'
      path: '/menu/add-menu'
      fullPath: '/menu/add-menu'
      preLoaderRoute: typeof MenuAddMenuImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/usermanagement': typeof UsermanagementRoute
  '/menu/add-menu': typeof MenuAddMenuRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/usermanagement': typeof UsermanagementRoute
  '/menu/add-menu': typeof MenuAddMenuRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/usermanagement': typeof UsermanagementRoute
  '/menu/add-menu': typeof MenuAddMenuRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/faq'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/usermanagement'
    | '/menu/add-menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/faq'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/usermanagement'
    | '/menu/add-menu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/faq'
    | '/feedback'
    | '/login'
    | '/signup'
    | '/usermanagement'
    | '/menu/add-menu'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UsermanagementRoute: typeof UsermanagementRoute
  MenuAddMenuRoute: typeof MenuAddMenuRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UsermanagementRoute: UsermanagementRoute,
  MenuAddMenuRoute: MenuAddMenuRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/faq",
        "/feedback",
        "/login",
        "/signup",
        "/usermanagement",
        "/menu/add-menu"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/usermanagement": {
      "filePath": "usermanagement.tsx"
    },
    "/menu/add-menu": {
      "filePath": "menu/add-menu.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
